### PR TITLE
Complete formatting fix

### PR DESCRIPTION
**Pull request by dschwartz783**
Speed up remedying your formatting woes.

### CODE REVIEW

**Comment by killer549** [comment]
Wait.

We are supposed to follow this[](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md) ?

**Comment by dschwartz783** [comment]
Ideally, yes.

**Comment by killer549** [comment]
So this should get accepted huh?

**Comment by dschwartz783** [comment]
Yes, the formatting is correct here. Unless I missed something. I don't think I did though.

**Comment by killer549** [comment]
umm.. Everything looks fine for me

Thank you so much for your help 😃

**Pull request merged**
